-- Creating user
CREATE OR REPLACE USER "tf-snow-user";
ALTER USER "tf-snow-user" SET RSA_PUBLIC_KEY='PUT_YOUR_PUBLIC_KEY_HERE';
-- Creating role
CREATE OR ALTER ROLE "TF-SNOW-ROLE";
-- Granting account privileges to the role
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "TF-SNOW-ROLE";
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "TF-SNOW-ROLE";
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE "TF-SNOW-ROLE";
-- Granting role to user
GRANT ROLE "TF-SNOW-ROLE" TO USER "tf-snow-user";
-- Setting the role as default
ALTER USER "tf-snow-user" SET DEFAULT_ROLE = "TF-SNOW-ROLE";
-- Showing privileges granted to role
SHOW GRANTS TO ROLE "TF-SNOW-ROLE";
-- Showing AWS IAM user 
CREATE STORAGE INTEGRATION DUMMY
TYPE = EXTERNAL_STAGE
ENABLED = TRUE
STORAGE_PROVIDER = "S3"
STORAGE_ALLOWED_LOCATIONS = ('*')
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::001234567890:role/myrole';

DESC INTEGRATION DUMMY;

DROP STORAGE INTEGRATION DUMMY;


