name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  TF_STATES_BASE_BUCKET_NAME: ${{ vars.TF_STATES_BASE_BUCKET_NAME }}

jobs:
  # Deploying AWS infrastructure
  aws_terraform:
    name: "AWS Infrastructure Change"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./aws
    permissions:
      issues: write
    
    env:
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}

      TF_VAR_snowflake_aws_user_arn: ${{ secrets.SNOWFLAKE_AWS_USER_ARN }}

      TF_VAR_reddit_username: ${{ secrets.REDDIT_USERNAME }}
      TF_VAR_reddit_password: ${{ secrets.REDDIT_PASSWORD }}
      TF_VAR_reddit_client_id: ${{ secrets.REDDIT_CLIENT_ID }}
      TF_VAR_reddit_client_secret: ${{ secrets.REDDIT_CLIENT_SECRET }}

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.10

      #Terraform initialisation 
      - name: Load environment variables
        id: load-vars
        run: source .config/.env.github && echo "Loaded config from .env.github"

      - name: Terraform init
        id: init
        env:
          AWS_TF_STATE_KEY: aws_${{ env.ENV }}/terraform.tfstate
        run: terraform init  -backend-config="region=$AWS_REGION" -backend-config="bucket=$TF_STATES_BASE_BUCKET_NAME" -backend-config="key=$AWS_TF_STATE_KEY"
      
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform validate
        id: validate
        run: terraform validate

      #Terraform planning
      - name: Terraform planning
        id: plan
        run: terraform plan -out aws_planfile
        continue-on-error: false    

      #Manual approval before applying plan if not by scheduler
      - if: github.event_name != 'schedule'
        name: Manual approval
        id: approve
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.ISSUE_WRITING_TOKEN }}
          approvers: ${{ vars.APPROVERS }}
          minimum-approvals: 1
          issue-title: "Deploying new terraform plan for AWS infrastructure"
          issue-body: "Please approve or deny the terraform deployment plan"
          exclude-workflow-initiator-as-approver: false

      #Export planfile
      - name: Export planfile
        id: export
        uses: actions/upload-artifact@v4
        with:
          path: aws/aws_planfile
          name: aws_planfile

      #Terraform applying
      - name: Terraform applying
        id: apply
        run: terraform apply aws_planfile


  # Deploying Snowflake infrastructure
  snowflake_terraform:
    name: "Snowflake Infrastructure Change"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./snowflake
    permissions:
      issues: write
    needs: aws_terraform

    env:
      SNOWFLAKE_ORG_NAME: ${{ vars.SNOWFLAKE_ORG_NAME }}
      SNOWFLAKE_ACCOUNT_NAME: ${{ vars.SNOWFLAKE_ACCOUNT_NAME }}

      TF_VAR_snowflake_private_key: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.10

      #Terraform initialisation 
      - name: Load environment variables
        id: load-vars
        run: source .config/.env.github && echo "Loaded config from .env.github"

      - name: Terraform init
        id: init
        env:
          SNOWFLAKE_TF_STATE_KEY: snowflake_${{ env.ENV }}/terraform.tfstate
        run: terraform init  -backend-config="region=$AWS_REGION" -backend-config="bucket=$TF_STATES_BASE_BUCKET_NAME" -backend-config="key=$SNOWFLAKE_TF_STATE_KEY"
      
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform validate
        id: validate
        run: terraform validate

      #Terraform planning
      - name: Terraform planning
        id: plan
        run: terraform plan -out snowflake_planfile
        continue-on-error: false

      #Manual approval before applying plan if not by scheduler
      - if: github.event_name != 'schedule'
        name: Manual approval
        id: approve
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.ISSUE_WRITING_TOKEN }}
          approvers: ${{ vars.APPROVERS }}
          minimum-approvals: 1
          issue-title: "Deploying new terraform plan for Snowflake infrastructure"
          issue-body: "Please approve or deny the terraform deployment plan"
          exclude-workflow-initiator-as-approver: false

      #Export planfile
      - name: Export planfile
        id: export
        uses: actions/upload-artifact@v4
        with:
          path: snowflake/snowflake_planfile
          name: snowflake_planfile

      #Terraform applying
      - name: Terraform applying
        id: apply
        run: terraform apply snowflake_planfile
